version: 2
jobs:
 first:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A first hello"
      - run: sleep 10
  second:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A second hello"
      - run: sleep 15
      
workflows:
  version: 2
  first_and_second:
    jobs:
      - first
      - second
